{
 "title": "API Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GET /todos success request rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(get_todos_success{instance=\"api:3000\",job=\"API\"}[1m])"
    }
   ]
  },
  {
   "title": "allocated memory",
   "type": "graph",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{instance=\"api:3000\",job=\"API\"}",
     "requestId": "Q-7b7affca-fc9f-43d7-98da-efe30d297ff9-0A"
    }
   ]
  },
  {
   "title": "prometheus metric requests rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total{code=\"200\",instance=\"api:3000\",job=\"API\"}[1m])"
    }
   ]
  }
 ]
}