---
apiVersion: v1
kind: Service
metadata:
  name: demo-service # Name of the resource
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: demo # Map any pod with label `app=demo` to this service
