---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo # This deployment applies to any Pods matching the specified label
  template: # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels: # The labels that will be applied to all of the pods in this deployment
        app: demo
    spec: # Spec for the container which will run in the Pod
      containers:
        - name: demo
          image: firasso/demo:v1
          imagePullPolicy: IfNotPresent
          # env: # uncomment for the first time to initialize some dummy data
          #   - name: INIT_DB
          #     value: "true"
          envFrom:
            - secretRef:
                name: env-secrets
          ports:
            - containerPort: 3000 # Should match the port number that the Go application listens on
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
